version: 2
jobs:
  Apollo Client:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Run Test and Coverage
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              chmod +x ./cc-test-reporter
              ./cc-test-reporter before-build --debug
              npm test
              node node_modules/codecov/bin/codecov
              cat ./coverage/lcov.info | node node_modules/codacy-coverage/bin/codacy-coverage.js
              cat ./coverage/lcov.info | node node_modules/coveralls/bin/coveralls.js
              ./cc-test-reporter after-build --debug --exit-code $?
            else
              npm test
            fi
      - run: 
          name: Run apollo engine checks
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npx apollo client:check
            fi
            if [ "${CIRCLE_BRANCH}" == "staging" ] || [ "${CIRCLE_BRANCH}" == "prod" ]; then
              npx apollo client:check --tag=${CIRCLE_BRANCH}
            fi
      - run: 
          name: Push to apollo engine
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npx apollo client:push
            fi
            if [ "${CIRCLE_BRANCH}" == "staging" ] || [ "${CIRCLE_BRANCH}" == "prod" ]; then
              npx apollo client:push --tag=${CIRCLE_BRANCH}
            fi

  CoPilot:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bash <(curl -s https://copilot.blackducksoftware.com/ci/circle2/scripts/upload)
            fi

  Heroku Deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/dev-$HEROKU_APP_NAME.git master
          elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/stage-$HEROKU_APP_NAME.git staging:master
          elif [ "${CIRCLE_BRANCH}" == "prod" ]; then
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/prod-$HEROKU_APP_NAME.git prod:master
          fi

workflows:
  version: 2
  Build and Test:
    jobs:
      - Apollo Client
      - CoPilot:
          requires:
            - Apollo Client
      - Heroku Deploy:
          requires:
            - CoPilot
