version: 2

jobs:
  Apollo Client:
    environment:
      CC_TEST_REPORTER_ID: $CC_TEST_REPORTER_ID
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run: # run tests
          name: Run Test and Coverage
          command: |
            ./cc-test-reporter before-build --debug
            npm test
            ./cc-test-reporter after-build --debug --exit-code $?
      - run: npx apollo client:check
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            npx apollo client:push
          fi

workflows:
  version: 2
  Build and Test:
    jobs:
      - Apollo Client
